name: Push-to-EC2

on: push

jobs:
    deploy:
        name: Push to EC2 Instance
        runs-on: ubuntu-latest

        steps:
            - name: Checkout the code
              uses: actions/checkout@v1

            - name: Deploy to my EC2 instance
              uses: easingthemes/ssh-deploy@v2.1.5
              env:
                  SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
                  SOURCE: './'
                  REMOTE_HOST: ${{ secrets.EC2_HOST }}
                  REMOTE_USER: ${{ secrets.EC2_USER }}
                  TARGET: ${{ secrets.EC2_TARGET }}

            - name: Install dependencies
              run: npm ci
    build:
        needs: deploy
            name: Build project in Kameground folder
            runs-on: ubuntu-latest

            steps:
              - name: Configure SSH
              run: |
                mkdir -p ~/.ssh/
                echo "$SSH_KEY" > ~/.ssh/github-actions-key
                chmod 600 ~/.ssh/github-actions-key
                cat >>~/.ssh/config <<END
                Host ec2
                  HostName $SSH_HOST
                  User $SSH_USER
                  IdentityFile ~/.ssh/github-actions-key
                  StrictHostKeyChecking no
                END
              env:
                SSH_HOST: ${{ env.EC2_HOST }}
                SSH_USER: ${{ env.EC2_USER }}
                SSH_KEY: ${{ secrets.EC2_SSH_KEY }} 

              - name: Build project
                run: ssh ubuntu@ec2-35-180-140-240.eu-west-3.compute.amazonaws.com /home/ubuntu/deploy.sh
