name: Push-to-EC2

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
    deploy:
        name: Push to EC2 Instance
        runs-on: ubuntu-latest

        steps:
            - name: Checkout the code
              uses: actions/checkout@v1

            - name: Deploy to my EC2 instance
              uses: easingthemes/ssh-deploy@v2.1.5
              env:
                  SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
                  SOURCE: './'
                  REMOTE_HOST: ${{ secrets.EC2_HOST }}
                  REMOTE_USER: ${{ secrets.EC2_USER }}
                  TARGET: ${{ secrets.EC2_TARGET }}

            - name: Install dependencies
              run: npm ci
    build:
        needs: deploy
        name: Build project in Kameground folder
        runs-on: ubuntu-latest

        steps:
            - name: Install SSH Key
              uses: shimataro/ssh-key-action@v2
              with:
                  key: ${{ secrets.EC2_SSH_KEY }}
                  known_hosts: 'placeholder'
            - name: Adding Known Hosts
              run: ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts
            - name: Run deploy script
              run: ssh ubuntu@${{ secrets.EC2_HOST }} bash deploy.sh
